apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-creator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sam@foo-corp.com
