apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    nomos.dev/cluster-name: e2e-test-cluster
    nomos.dev/source-path: cluster/namespace-viewer-clusterrole.yaml
    nomos.dev/sync-token: 1fac9275554f285518c621fe20b4e14202d74bee
  name: namespace-viewer
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
