apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    nomos.dev/cluster-name: e2e-test-cluster
    nomos.dev/source-path: cluster/podsecuritypolicy.yaml
    nomos.dev/sync-token: 1fac9275554f285518c621fe20b4e14202d74bee
  name: example
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
